name: Android CI Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.0

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # Add steps for setting up signing configuration if necessary

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Find APK
      id: find_apk
      run: |
        APK_PATH=$(find . -name "*-release.apk" | head -n 1)
        if [ -z "$APK_PATH" ]; then
          echo "No APK found"
          exit 1
        fi
        echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
        echo "Found APK at $APK_PATH"

    - name: Upload APK
      if: env.APK_PATH != ''
      uses: actions/upload-artifact@v2
      with:
        name: Release APK
        path: ${{ env.APK_PATH }}
